# Generated by Django 5.0.7 on 2024-07-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='name',
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='base.category'),
        ),
        migrations.AddField(
            model_name='bot',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='bot',
            name='contact_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='excelsheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='bot',
            name='profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='base.useruuid'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
