# Generated by Django 5.0.7 on 2024-07-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_bot_admin_remove_bot_category_remove_bot_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
