# Generated by Django 5.0 on 2024-07-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='sys_ins',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='excelsheet',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='profile',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
