# Generated by Django 5.0.7 on 2024-07-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_bot_sys_ins_alter_bot_excelsheet_alter_bot_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated', 'created']},
        ),
    ]
